[package]
name = "sqlx_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.7.3", features = ["postgres", "time", "chrono", "runtime-tokio"] }
tokio = { version = "1.35.1", features = ["full"] }

[build-dependencies]
dotenv = {version = "*"}